### ISSUE TITLE
Turn a given angle autonomously

### ISSUE THREAD

**Issue by WebCoder49** [brightonfrc/2024#5]
|||
|-|-|
|Type|Autonomous|
|Input|Angle for robot to turn|
|Sensors|Swerve drivetrain encoder positions, IMU readings, Distance sensor readings (optional extension), April Tag readings (optional extension)|
|Output|Swerve drive motor powers|
|Hardware|We are using [REV MAXSwerve modules](https://www.revrobotics.com/rev-21-3005/) for the drivetrain, a NavX2 MXP IMU, and Maxbotix LV-MaxSonar-EZ distance sensors.|
|Team|@brightonfrc/team-2|

Please remember to follow [our GitHub flow](https://github.com/BrightonFRC/2024/wiki/Using-Branches,-Pull-Requests,-and-Merging#our-flow-coding) and if you're stuck, use [the wiki resources](https://github.com/BrightonFRC/2024/wiki), [documentation](https://github.com/BrightonFRC/2024/wiki/Documentation), or ask others on Teams.

**Comment by WebCoder49** [comment]
Please be careful! A swerve drive is not the same as the differential drive we were using earlier.

**Comment by ethanharjabrata** [comment]
Here is the library for the 2024 versions of the vendor libraries
https://github.com/wpilibsuite/2024Beta

**Comment by WebCoder49** [comment]
If you have any questions you may ask @spamtactics who created the swerve drivetrain code, @brightonfrc/team-2 .
