### ISSUE TITLE
Driver-controlled swerve drive

### ISSUE THREAD

**Issue by WebCoder49** [brightonfrc/2024#7]
|||
|-|-|
|Type|Driver-Controlled|
|Input|Joystick values|
|Sensors|Swerve drivetrain encoder positions (optional extension), IMU readings (optional extension)|
|Output|Swerve drive motor powers|
|Hardware|We are using [REV MAXSwerve modules](https://www.revrobotics.com/rev-21-3005/) for the drivetrain, and a NavX2 MXP IMU.|
|Team|@brightonfrc/team-4|

Please remember to follow [our GitHub flow](https://github.com/BrightonFRC/2024/wiki/Using-Branches,-Pull-Requests,-and-Merging#our-flow-coding) and if you're stuck, use [the wiki resources](https://github.com/BrightonFRC/2024/wiki), [documentation](https://github.com/BrightonFRC/2024/wiki/Documentation), or ask others on Teams.

**Comment by WebCoder49** [comment]
Although not vital, the sensors here could help you ensure your driving is straight and turns enough. Additionally, is your drive direction going to be relative to the robot, or global relative to the field?

**Comment by ethanharjabrata** [comment]
Would it be easier if the robot was field-oriented?
